config/routes.rb
Rails.application.routes.draw do
  resources :games
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  devise_for :users
  root to: "home#index"
  get '/history', to: 'games#index'
  get '/log',     to: 'games#new'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :game
  
  after_initialize :init
  
  def init
    self.rating ||= 0.0 
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

  # GET /games
  # GET /games.json
  def index
    
    currentUser = current_user.id
    
    @user = User.find(currentUser)
    
    @games =  @user.game #Game.users
  end

  # GET /games/1
  # GET /games/1.json
  def show
  end

  # GET /games/new
  def new
    @game = Game.new
  end

  # GET /games/1/edit
  def edit
  end

  # POST /games
  # POST /games.json
  def create
    @game = Game.new(game_params)
    
    user_score =  params[:game][:user1_score]
    user2_score = params[:game][:user2_score]
    
    if ( user_score > user2_score)
      @game.winner = params[:game][:user_id]
    else
      @game.winner = params[:game][:user2_id]
    end
  
    user = User.find(@game.winner)
    
    user.rating += 1
    
    user.save
    
    respond_to do |format|
      if @game.save
        format.html { redirect_to '/history', notice: 'Game was successfully created.' }
        format.json { render :show, status: :created, location: @game }
      else
        format.html { render :new }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /games/1
  # PATCH/PUT /games/1.json
  def update
    respond_to do |format|
      if @game.update(game_params)
        format.html { redirect_to @game, notice: 'Game was successfully updated.' }
        format.json { render :show, status: :ok, location: @game }
      else
        format.html { render :edit }
        format.json { render json: @game.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /games/1
  # DELETE /games/1.json
  def destroy
    @game.destroy
    respond_to do |format|
      format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_game
      @game = Game.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def game_params
      params.require(:game).permit(:user_id, :user2_id, :user1_score, :user2_score, :winner)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @users = User.order(rating: :desc ).all
  end

  def history
  end

  def log
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/_form.html.erb
<%= form_with(model: game, local: true, :html => {:class => "form-horizontal"}) do |form| %>
  <% if game.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(game.errors.count, "error") %> prohibited this game from being saved:</h2>

      <ul>
      <% game.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group hidden">
    <% @currentUser = current_user.id %>
    <%= form.label "Your id:",class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.number_field :user_id, id: :game_user_id, class: 'form-control', value: @currentUser %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label 'Opponent Id:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.number_field :user2_id, id: :game_user2_id, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label 'Your Score:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.number_field :user1_score, id: :game_user1_score, class: 'form-control' %>
    </div>
  </div>

  <div class="form-group">
    <%= form.label 'Their Score:', class: 'col-sm-2 control-label' %>
    <div class="col-sm-10">
      <%= form.number_field :user2_score, id: :game_user2_score, class: 'form-control' %>
    </div>
  </div>

  

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <%= form.submit "Save", class: 'btn btn-primary' %>
    </div>
  </div>
<% end %>

app/views/games/edit.html.erb
<h1>Editing Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Show', @game %> |
<%= link_to 'Back', games_path %>

app/views/games/index.html.erb
<h1 class='page-header'>History</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Date</th>
      <th>Opponent</th>
      <th>score</th>
      <th>Result</th>
    </tr>
  </thead>

  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= game.created_at %></td>
        <td><%= game.user2_id %></td>
        <td><%= "#{game.user1_score} - #{game.user2_score}" %></td>
        <td><%= 'W' if game.winner == @user.id %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/games/new.html.erb
<h1 class='page-header'>Log Game</h1>

<%= render 'form', game: @game %>

<%= link_to 'Back', games_path %>

app/views/games/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User1:</strong>
  <%= @game.user1_id %>
</p>

<p>
  <strong>User2:</strong>
  <%= @game.user2_id %>
</p>

<p>
  <strong>User1 score:</strong>
  <%= @game.user1_score %>
</p>

<p>
  <strong>User2 score:</strong>
  <%= @game.user2_score %>
</p>

<p>
  <strong>Winner:</strong>
  <%= @game.winner %>
</p>

<%= link_to 'Edit', edit_game_path(@game) %> |
<%= link_to 'Back', games_path %>

app/views/home/history.html.erb
<h1 class='page-header'>History</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%# image_tag('history.png') %>

app/views/home/index.html.erb
<h1 class='page-header'>Leaderboard</h1>

<table class="table table-striped table-bordered">
  <thead>
    <tr>
      <th>Rank</th>
      <th>Id</th>
      <th>Email</th>
      <th>score</th>
      <th>Games Played</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each_with_index do |user, index| %>
      <tr>
        <td><%= index+1 %></td>
        <td><%= user.id %></td>
        <td><%= user.email %></td>
        <td><%= user.rating %></td>
        <td><%= user.game.length %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/home/log.html.erb
<h1 class='page-header'>Log Game</h1>

<div class="alert alert-warning" role="alert">This is a sample page. Replace link in the header with your own.</div>

<%# image_tag('log_game.png') %>
<%# render 'form', game: @game %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Pingpong</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <%= link_to 'Log Game', '/log', class: 'btn btn-success navbar-btn' %>
      <ul class="nav navbar-nav">
        <% if user_signed_in? %>
          <li><%= link_to 'Leadboard', root_path %></li>
        <% end %>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><a href="/history">History</a></li>
          <li><%= link_to 'Logout', destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to 'Login', new_user_session_path %></li>
          <li><%= link_to 'Sign up', new_user_registration_path %></li>
        <% end %>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Pingpong Leaderboard</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/css/bootstrap.min.css", integrity: "sha512-dTfge/zgoMYpP7QbHy4gWMEGsbsdZeCXz7irItjcC3sPUFtf0kuFbDz/ixG7ArTxmDjLXDmezHubeNikyKGVyQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.3.5/js/bootstrap.min.js", integrity: "sha512-K1qjQ+NcF2TYO/eI3M6v8EiNYZfA95pQumfvcVrTHtwQVDG+aHRqLi/ETn2uB+1JqwYqVG3LIvdm9lj6imS/pQ==", crossorigin: "anonymous" %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>

  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>

  <div class='container'>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </div>
</body>
</html>